name: Build SCSS

on:
  push:
    paths:
      - '*.scss'
      - '*/*.scss'
  pull_request:
    paths:
      - '*.scss'
      - '*/*.scss'

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install Dependencies"
        run: make install
      - name: "Build Files"
        run: make build
